// oxlint-disable no-underscore-dangle
/* eslint-disable @typescript-eslint/naming-convention */
import { MCPServer } from 'mcp-use';
import { z } from 'zod';

import { CommandDispatcher } from './src/CommandDispatcher.js';
import { validateConfigurations } from './src/validate_configurations.js';
import { WebSocketTelemetryServer } from './src/WebSocketTelemetryServer.js';

const server = new MCPServer({
    name: 'scenegrid-mcp-server',
    title: 'SceneGrid MCP Server',
    version: '1.0.0',
    description: 'SceneGrid diagnostic and orchestration tools',
    instructions: 'use show-app to open the app view',
    websiteUrl: 'https://mcp-use.com',
    icons: [
        {
            src: 'icon.svg',
            mimeType: 'image/svg+xml',
            sizes: ['512x512']
        }
    ]
});

const telemetryServer = new WebSocketTelemetryServer(8081);

const isBuilding = process.argv.some(arg => arg.includes('build'));

declare global {
    var __telemetryServer: WebSocketTelemetryServer | undefined;
}

if (!isBuilding) {
    const startServer = async () => {
        if (globalThis.__telemetryServer) {
            console.log('[TelemetryServer] HMR: Stopping previous server...');
            try {
                await globalThis.__telemetryServer.stop();
            } catch (err) {
                console.error('[TelemetryServer] Error stopping previous server:', err);
            }
        }

        globalThis.__telemetryServer = telemetryServer;

        try {
            await telemetryServer.start();
        } catch (err) {
            console.error('Failed to start telemetry server:', err);
        }
    };

    void startServer();

    const shutdown = async (signal?: string) => {
        console.log(`[TelemetryServer] Gracefully shutting down (signal: ${signal})...`);
        try {
            await telemetryServer.stop();
            globalThis.__telemetryServer = undefined;
            if (signal === 'SIGUSR2') {
                process.kill(process.pid, 'SIGUSR2');
            } else if (signal) {
                process.exit(0);
            }
        } catch (err) {
            console.error('[TelemetryServer] Error during shutdown:', err);
            if (signal) process.exit(1);
        }
    };

    process.once('SIGINT', () => shutdown('SIGINT'));
    process.once('SIGTERM', () => shutdown('SIGTERM'));
    process.once('SIGUSR2', () => shutdown('SIGUSR2'));
}

const dispatcher = new CommandDispatcher(telemetryServer);

server.use('mcp:tools/call', async (ctx, next) => {
    const result = await next();
    console.log(`[mcp:tools/call] ${ctx.params?.name} result:`, JSON.stringify(result));
    return result;
});

import {
    getConsistencyReportHandler,
    getManifestHandler,
    getTelemetryLiveHandler,
    getRamReportHandler,
    triggerEventHandler,
    setRtpcValueHandler,
    stopAllSoundsHandler,
    pauseEngineHandler,
    resumeEngineHandler,
    applyMixerSnapshotHandler,
    getDebugAudioIssuePrompt
} from './src/runtime_tools.js';

server.resource(
    {
        uri: 'scenegrid://manifest/current',
        name: 'engine-manifest',
        description: 'Always up-to-date static JSON manifest including banks, events, buses, and global settings'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const data = await getManifestHandler(telemetryServer);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'application/json',
                    text: JSON.stringify(data, null, 2)
                }
            ]
        };
    }
);

server.resource(
    {
        uri: 'scenegrid://telemetry/live',
        name: 'telemetry-live',
        description: 'Current active playbacks (voices), buses, and RTPCs in the engine'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const data = await getTelemetryLiveHandler(telemetryServer);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'application/json',
                    text: JSON.stringify(data, null, 2)
                }
            ]
        };
    }
);

server.resource(
    {
        uri: 'scenegrid://validation/latest',
        name: 'validation-latest',
        description: 'Latest consistency and validation report generated by the engine'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const data = await getConsistencyReportHandler(telemetryServer);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'application/json',
                    text: JSON.stringify(data, null, 2)
                }
            ]
        };
    }
);

server.resource(
    {
        uri: 'scenegrid://ram/budget',
        name: 'ram-budget',
        description: 'Current memory status (usedBytes / maxQuotaBytes)'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const data = await getRamReportHandler(telemetryServer);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'application/json',
                    text: JSON.stringify(data, null, 2)
                }
            ]
        };
    }
);

export const triggerEvent = server.tool(
    {
        name: 'trigger_event',
        title: 'Trigger Event',
        description: 'Fires an event by eventId through the command dispatcher.',
        inputSchema: z.object({
            eventId: z.string().describe('The ID of the event to trigger')
        }),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }
    },
    async ({ eventId }) => {
        await triggerEventHandler(dispatcher, eventId);
        return {
            content: [{ type: 'text', text: `Event ${eventId} triggered.` }],
            structuredContent: { success: true }
        };
    }
);

export const setRtpcValue = server.tool(
    {
        name: 'set_rtpc_value',
        title: 'Set RTPC Value',
        description: 'Sets the value of an RTPC parameter.',
        inputSchema: z.object({
            param: z.string().describe('The RTPC parameter name'),
            value: z.number().describe('The numerical value to set')
        }),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }
    },
    async ({ param, value }) => {
        await setRtpcValueHandler(dispatcher, param, value);
        return {
            content: [{ type: 'text', text: `RTPC ${param} set to ${value}.` }],
            structuredContent: { success: true }
        };
    }
);

export const stopAllSounds = server.tool(
    {
        name: 'stop_all_sounds',
        title: 'Stop All Sounds',
        description: 'Global emergency stop for all physical voices in the engine.',
        inputSchema: z.object({}),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
        view: { name: 'my-view' }
    },
    async () => {
        await stopAllSoundsHandler(dispatcher);
        return {
            content: [{ type: 'text', text: 'All sounds stopped.' }],
            structuredContent: { success: true }
        };
    }
);

export const pauseEngine = server.tool(
    {
        name: 'pause_engine',
        title: 'Pause Engine',
        description: 'Freezes the EngineTicker, pausing all audio processing.',
        inputSchema: z.object({}),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }
    },
    async () => {
        await pauseEngineHandler(dispatcher);
        return {
            content: [{ type: 'text', text: 'Engine paused.' }],
            structuredContent: { success: true }
        };
    }
);

export const resumeEngine = server.tool(
    {
        name: 'resume_engine',
        title: 'Resume Engine',
        description: 'Resumes the EngineTicker.',
        inputSchema: z.object({}),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }
    },
    async () => {
        await resumeEngineHandler(dispatcher);
        return {
            content: [{ type: 'text', text: 'Engine resumed.' }],
            structuredContent: { success: true }
        };
    }
);

export const applyMixerSnapshot = server.tool(
    {
        name: 'apply_mixer_snapshot',
        title: 'Apply Mixer Snapshot',
        description: 'Activates a mixer VCA snapshot with a transition over the specified time.',
        inputSchema: z.object({
            snapshotId: z.string().describe('The ID of the snapshot to apply'),
            transitionTimeMs: z.number().optional().describe('Transition time in milliseconds')
        }),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }
    },
    async ({ snapshotId, transitionTimeMs }) => {
        await applyMixerSnapshotHandler(dispatcher, snapshotId, transitionTimeMs);
        return {
            content: [{ type: 'text', text: `Snapshot ${snapshotId} applied.` }],
            structuredContent: { success: true }
        };
    }
);

export const validateConfigurationsTool = server.tool(
    {
        name: 'validate_configurations',
        title: 'Validate Configurations',
        description: 'Validates a JSON configuration payload against the SceneGrid engine ConsistencyChecker.',
        inputSchema: z.object({
            payload: z.any().describe('The JSON configuration payload to validate')
        }),
        outputSchema: z.object({
            errors: z.array(z.string()),
            warnings: z.array(z.string())
        }),
        annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }
    },
    async ({ payload }) => {
        const report = await validateConfigurations(payload);
        return {
            content: [{ type: 'text', text: JSON.stringify(report, null, 2) }],
            structuredContent: report
        };
    }
);

server.prompt(
    {
        name: 'debug-audio-issue',
        description: 'Guided instructions for troubleshooting missing or incorrect audio playback'
    },
    async () => {
        const text = await getDebugAudioIssuePrompt();
        return {
            messages: [
                {
                    role: 'user',
                    content: {
                        type: 'text',
                        text
                    }
                }
            ]
        };
    }
);

import {
    processAssetsHandler,
    generateAliasesHandler,
    inspectPcmWeightHandler,
    getQuotaPreviewHandler
} from './src/runtime_tools.js';

export const getQuotaPreviewTool = server.tool(
    {
        name: 'get_quota_preview',
        title: 'Get Quota Preview',
        description:
            'Generates a dry-run report showing how memory will be allocated between AudioBuffer and ChunkedStream.',
        inputSchema: z.object({
            inputDir: z.string().describe('Directory containing raw audio files'),
            quotaMb: z.number().describe('RAM quota limit in megabytes'),
            streamRules: z.array(z.string()).describe('Regex patterns for files to stream'),
            streamExclusions: z.array(z.string()).describe('Regex patterns for files to exclude from streaming')
        }),
        outputSchema: z.object({
            totalMemoryMb: z.number(),
            files: z.record(
                z.string(),
                z.object({
                    sizeMb: z.number(),
                    route: z.enum(['ladder', 'chunk'])
                })
            )
        }),
        annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }
    },
    async ({ inputDir, quotaMb, streamRules, streamExclusions }) => {
        const report = await getQuotaPreviewHandler(inputDir, quotaMb, streamRules, streamExclusions);
        return {
            content: [{ type: 'text', text: JSON.stringify(report, null, 2) }],
            structuredContent: report
        };
    }
);

export const processAssetsTool = server.tool(
    {
        name: 'process_assets',
        title: 'Process Audio Assets',
        description: 'Runs the AOT audio asset processing pipeline programmatically.',
        inputSchema: z.object({
            inputDir: z.string().describe('Directory containing raw audio files'),
            outputDir: z.string().describe('Output directory for processed audio files'),
            manifestsDir: z.string().describe('Output directory for JSON manifests'),
            quotaMb: z.number().describe('RAM quota limit in megabytes'),
            streamRules: z.array(z.string()).describe('Regex patterns for files to stream'),
            streamExclusions: z.array(z.string()).describe('Regex patterns for files to exclude from streaming'),
            streamPriority: z.enum(['high', 'low']).optional(),
            hash: z.boolean().optional(),
            baseUrl: z.string().optional(),
            aliases: z.string().optional()
        }),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }
    },
    async options => {
        await processAssetsHandler(options);
        return {
            content: [{ type: 'text', text: 'Audio assets processed successfully.' }],
            structuredContent: { success: true }
        };
    }
);

export const generateAliasesTool = server.tool(
    {
        name: 'generate_aliases',
        title: 'Generate Sound Aliases',
        description: 'Scans a directory of WAV files and generates a SoundId aliases JSON file.',
        inputSchema: z.object({
            inputDir: z.string().describe('Directory containing raw audio files'),
            outputPath: z.string().describe('Output JSON file path for aliases')
        }),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }
    },
    async ({ inputDir, outputPath }) => {
        await generateAliasesHandler(inputDir, outputPath);
        return {
            content: [{ type: 'text', text: `Aliases generated at ${outputPath}` }],
            structuredContent: { success: true }
        };
    }
);

export const inspectPcmWeightTool = server.tool(
    {
        name: 'inspect_pcm_weight',
        title: 'Inspect PCM Weight',
        description: 'Calculates the uncompressed RAM footprint of a raw audio file.',
        inputSchema: z.object({
            filePath: z.string().describe('Path to the raw audio file (WAV/OGG/MP3)')
        }),
        outputSchema: z.object({
            durationSec: z.number(),
            channels: z.number(),
            sampleRate: z.number(),
            exactSizeMb: z.number(),
            exactSizeBytes: z.number()
        }),
        annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }
    },
    async ({ filePath }) => {
        const report = await inspectPcmWeightHandler(filePath);
        return {
            content: [{ type: 'text', text: JSON.stringify(report, null, 2) }],
            structuredContent: report
        };
    }
);

export default server;

import {
    contextConventionsHandler,
    getSchemaHandler,
    queryGraphHandler,
    traceEventHandler,
    recordSessionTelemetryHandler
} from './src/runtime_tools.js';

server.resource(
    {
        uri: 'scenegrid://context/conventions',
        name: 'agent-conventions',
        description: 'Dynamically reads the project AGENTS.md conventions'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const workspaceRoot = process.cwd();
        const data = await contextConventionsHandler(workspaceRoot);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'text/markdown',
                    text: data
                }
            ]
        };
    }
);

export const getSchemaTool = server.tool(
    {
        name: 'get_schema',
        title: 'Get Engine Schema',
        description: 'Exposes the pre-generated JSON Schema for the engine configuration',
        inputSchema: z.object({
            variant: z.enum(['referenced', 'dereferenced']).default('referenced'),
            targetSlice: z.string().optional()
        })
    },
    async ({ variant, targetSlice }) => {
        const schema = await getSchemaHandler(variant, targetSlice);
        return {
            content: [{ type: 'text', text: JSON.stringify(schema, null, 2) }],
            structuredContent: schema
        };
    }
);

export const queryGraphTool = server.tool(
    {
        name: 'query_graph',
        title: 'Query Manifest Graph',
        description: 'Fetches localized manifest branches using dot-notation (e.g. buses.sfx)',
        inputSchema: z.object({
            queryPath: z.string()
        })
    },
    async ({ queryPath }) => {
        const result = await queryGraphHandler(telemetryServer, queryPath);
        return {
            content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
            structuredContent: result
        };
    }
);

export const traceEventTool = server.tool(
    {
        name: 'trace_event',
        title: 'Trace Event History',
        description: 'Returns recent history of CAUSE_CHAIN and LIFECYCLE events',
        inputSchema: z.object({})
    },
    async () => {
        const history = await traceEventHandler(telemetryServer);
        return {
            content: [{ type: 'text', text: JSON.stringify(history, null, 2) }],
            structuredContent: history
        };
    }
);

export const recordSessionTelemetryTool = server.tool(
    {
        name: 'record_session_telemetry',
        title: 'Record Session Telemetry',
        description: 'Starts or stops telemetry buffering',
        inputSchema: z.object({
            state: z.enum(['start', 'stop'])
        })
    },
    async ({ state }) => {
        const result = await recordSessionTelemetryHandler(telemetryServer, state);
        return {
            content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
            structuredContent: result
        };
    }
);

