// oxlint-disable no-underscore-dangle
/* eslint-disable @typescript-eslint/naming-convention */
import { MCPServer } from 'mcp-use';
import { z } from 'zod';

import { CommandDispatcher } from './src/CommandDispatcher.js';
import { validateConfigurations } from './src/validate_configurations.js';
import { WebSocketTelemetryServer } from './src/WebSocketTelemetryServer.js';

const server = new MCPServer({
    name: 'scenegrid-mcp-server',
    title: 'SceneGrid MCP Server',
    version: '1.0.0',
    description: 'SceneGrid diagnostic and orchestration tools',
    instructions: 'use show-app to open the app view',
    websiteUrl: 'https://mcp-use.com',
    icons: [
        {
            src: 'icon.svg',
            mimeType: 'image/svg+xml',
            sizes: ['512x512']
        }
    ]
});

const telemetryServer = new WebSocketTelemetryServer(8081);

const isBuilding = process.argv.some(arg => arg.includes('build'));

declare global {
    var __telemetryServer: WebSocketTelemetryServer | undefined;
}

if (!isBuilding) {
    const startServer = async () => {
        if (globalThis.__telemetryServer) {
            console.log('[TelemetryServer] HMR: Stopping previous server...');
            try {
                await globalThis.__telemetryServer.stop();
            } catch (err) {
                console.error('[TelemetryServer] Error stopping previous server:', err);
            }
        }

        globalThis.__telemetryServer = telemetryServer;

        try {
            await telemetryServer.start();
        } catch (err) {
            console.error('Failed to start telemetry server:', err);
        }
    };

    void startServer();

    const shutdown = async (signal?: string) => {
        console.log(`[TelemetryServer] Gracefully shutting down (signal: ${signal})...`);
        try {
            await telemetryServer.stop();
            globalThis.__telemetryServer = undefined;
            if (signal === 'SIGUSR2') {
                process.kill(process.pid, 'SIGUSR2');
            } else if (signal) {
                process.exit(0);
            }
        } catch (err) {
            console.error('[TelemetryServer] Error during shutdown:', err);
            if (signal) process.exit(1);
        }
    };

    process.once('SIGINT', () => shutdown('SIGINT'));
    process.once('SIGTERM', () => shutdown('SIGTERM'));
    process.once('SIGUSR2', () => shutdown('SIGUSR2'));
}

const dispatcher = new CommandDispatcher(telemetryServer);

server.use('mcp:tools/call', async (ctx, next) => {
    const result = await next();
    console.log(`[mcp:tools/call] ${ctx.params?.name} result:`, JSON.stringify(result));
    return result;
});

import {
    getConsistencyReportHandler,
    getManifestHandler,
    getTelemetryLiveHandler,
    getRamReportHandler,
    triggerEventHandler,
    setRtpcValueHandler,
    stopAllSoundsHandler,
    pauseEngineHandler,
    resumeEngineHandler,
    applyMixerSnapshotHandler,
    getDebugAudioIssuePrompt
} from './src/runtime_tools.js';

server.resource(
    {
        uri: 'scenegrid://manifest/current',
        name: 'engine-manifest',
        description: 'Always up-to-date static JSON manifest including banks, events, buses, and global settings'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const data = await getManifestHandler(telemetryServer);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'application/json',
                    text: JSON.stringify(data, null, 2)
                }
            ]
        };
    }
);

server.resource(
    {
        uri: 'scenegrid://telemetry/live',
        name: 'telemetry-live',
        description: 'Current active playbacks (voices), buses, and RTPCs in the engine'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const data = await getTelemetryLiveHandler(telemetryServer);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'application/json',
                    text: JSON.stringify(data, null, 2)
                }
            ]
        };
    }
);

server.resource(
    {
        uri: 'scenegrid://validation/latest',
        name: 'validation-latest',
        description: 'Latest consistency and validation report generated by the engine'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const data = await getConsistencyReportHandler(telemetryServer);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'application/json',
                    text: JSON.stringify(data, null, 2)
                }
            ]
        };
    }
);

server.resource(
    {
        uri: 'scenegrid://ram/budget',
        name: 'ram-budget',
        description: 'Current memory status (usedBytes / maxQuotaBytes)'
    },
    // oxlint-disable-next-line no-unused-vars
    async (uri, ctx) => {
        const data = await getRamReportHandler(telemetryServer);
        return {
            contents: [
                {
                    uri: uri.href,
                    mimeType: 'application/json',
                    text: JSON.stringify(data, null, 2)
                }
            ]
        };
    }
);

export const triggerEvent = server.tool(
    {
        name: 'trigger_event',
        title: 'Trigger Event',
        description: 'Fires an event by eventId through the command dispatcher.',
        inputSchema: z.object({
            eventId: z.string().describe('The ID of the event to trigger')
        }),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }
    },
    async ({ eventId }) => {
        await triggerEventHandler(dispatcher, eventId);
        return {
            content: [{ type: 'text', text: `Event ${eventId} triggered.` }],
            structuredContent: { success: true }
        };
    }
);

export const setRtpcValue = server.tool(
    {
        name: 'set_rtpc_value',
        title: 'Set RTPC Value',
        description: 'Sets the value of an RTPC parameter.',
        inputSchema: z.object({
            param: z.string().describe('The RTPC parameter name'),
            value: z.number().describe('The numerical value to set')
        }),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }
    },
    async ({ param, value }) => {
        await setRtpcValueHandler(dispatcher, param, value);
        return {
            content: [{ type: 'text', text: `RTPC ${param} set to ${value}.` }],
            structuredContent: { success: true }
        };
    }
);

export const stopAllSounds = server.tool(
    {
        name: 'stop_all_sounds',
        title: 'Stop All Sounds',
        description: 'Global emergency stop for all physical voices in the engine.',
        inputSchema: z.object({}),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
        view: { name: 'my-view' }
    },
    async () => {
        await stopAllSoundsHandler(dispatcher);
        return {
            content: [{ type: 'text', text: 'All sounds stopped.' }],
            structuredContent: { success: true }
        };
    }
);

export const pauseEngine = server.tool(
    {
        name: 'pause_engine',
        title: 'Pause Engine',
        description: 'Freezes the EngineTicker, pausing all audio processing.',
        inputSchema: z.object({}),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }
    },
    async () => {
        await pauseEngineHandler(dispatcher);
        return {
            content: [{ type: 'text', text: 'Engine paused.' }],
            structuredContent: { success: true }
        };
    }
);

export const resumeEngine = server.tool(
    {
        name: 'resume_engine',
        title: 'Resume Engine',
        description: 'Resumes the EngineTicker.',
        inputSchema: z.object({}),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false }
    },
    async () => {
        await resumeEngineHandler(dispatcher);
        return {
            content: [{ type: 'text', text: 'Engine resumed.' }],
            structuredContent: { success: true }
        };
    }
);

export const applyMixerSnapshot = server.tool(
    {
        name: 'apply_mixer_snapshot',
        title: 'Apply Mixer Snapshot',
        description: 'Activates a mixer VCA snapshot with a transition over the specified time.',
        inputSchema: z.object({
            snapshotId: z.string().describe('The ID of the snapshot to apply'),
            transitionTimeMs: z.number().optional().describe('Transition time in milliseconds')
        }),
        outputSchema: z.object({ success: z.boolean() }),
        annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false }
    },
    async ({ snapshotId, transitionTimeMs }) => {
        await applyMixerSnapshotHandler(dispatcher, snapshotId, transitionTimeMs);
        return {
            content: [{ type: 'text', text: `Snapshot ${snapshotId} applied.` }],
            structuredContent: { success: true }
        };
    }
);

export const validateConfigurationsTool = server.tool(
    {
        name: 'validate_configurations',
        title: 'Validate Configurations',
        description: 'Validates a JSON configuration payload against the SceneGrid engine ConsistencyChecker.',
        inputSchema: z.object({
            payload: z.any().describe('The JSON configuration payload to validate')
        }),
        outputSchema: z.object({
            errors: z.array(z.string()),
            warnings: z.array(z.string())
        }),
        annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false }
    },
    async ({ payload }) => {
        const report = await validateConfigurations(payload);
        return {
            content: [{ type: 'text', text: JSON.stringify(report, null, 2) }],
            structuredContent: report
        };
    }
);

server.prompt(
    {
        name: 'debug-audio-issue',
        description: 'Guided instructions for troubleshooting missing or incorrect audio playback'
    },
    async () => {
        const text = await getDebugAudioIssuePrompt();
        return {
            messages: [
                {
                    role: 'user',
                    content: {
                        type: 'text',
                        text
                    }
                }
            ]
        };
    }
);

export default server;
