// Generated by mcp-use. Do not edit.
// oxlint-disable-next-line import/no-unassigned-import
import 'mcp-use/vite-client';

declare module 'mcp-use/react' {
    interface Register {
        tools: typeof import('./index.js');
    }
}

// oxlint-disable-next-line unicorn/require-module-specifiers
export {};
